# Generated by Django 5.2 on 2025-04-05 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_cad", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
